name: Android CI

on:
  workflow_dispatch:
    inputs:
      test1:
        description: 'Test1'
        type: boolean
      test2:
        description: 'Test2'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: grant permissions for gradle
        run: chmod +x gradlew
      - name: build debug build
        run: ./gradlew assembleDebug
      - name: upload build to firebase app distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
          appId: ${{secrets.FIREBASE_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk